/**
 * Export utilities for Synthesis OS nodes.
 * Convert nodes to Markdown, JSON, and handle clipboard operations.
 */

import { SynthesisNode, UIBlock } from "@/types/synthesis";

function blockToMarkdown(block: UIBlock): string {
    switch (block.type) {
        case "hero_image":
            return `![${block.caption || "Image"}](${block.url})${block.caption ? `\n*${block.caption}*` : ""}`;

        case "text_block":
            if (!block.content) return "";
            switch (block.style) {
                case "h1":
                    return `# ${block.content}`;
                case "h2":
                    return `## ${block.content}`;
                case "quote":
                    return `> ${block.content}`;
                case "caption":
                    return `*${block.content}*`;
                case "body":
                case "none":
                default:
                    return block.content;
            }

        case "data_grid": {
            if (!block.items || block.items.length === 0) return "";
            const rows = block.items
                .map((item) => `| ${item.label} | ${item.value} |`)
                .join("\n");
            return `| Field | Value |\n|-------|-------|\n${rows}`;
        }

        case "action_row":
            if (!block.actions || block.actions.length === 0) return "";
            return block.actions
                .map((action) => {
                    if (action.intent.startsWith("http")) {
                        return `[${action.label}](${action.intent})`;
                    }
                    return `- ${action.label}`;
                })
                .join("\n");

        case "list_block":
            if (!block.items || block.items.length === 0) return "";
            return block.items
                .map((item, idx) => {
                    let text = "";
                    if (typeof item === "string") {
                        text = item;
                    } else if ("text" in item && typeof item.text === "string" && item.text) {
                        text = item.text;
                    } else {
                        const rec = item as Record<string, unknown>;
                        const label = typeof rec.label === "string" ? rec.label : "";
                        const value = typeof rec.value === "string" ? rec.value : "";
                        text = label || value;
                    }
                    return `${block.ordered ? `${idx + 1}.` : "-"} ${text}`;
                })
                .join("\n");

        case "code_block":
            if (!block.code) return "";
            return `\`\`\`${block.language || ""}\n${block.code}\n\`\`\``;

        case "table_block":
            if (!block.headers?.length || !block.rows?.length) return "";
            return [
                `| ${block.headers.join(" | ")} |`,
                `| ${block.headers.map(() => "---").join(" | ")} |`,
                ...block.rows.map((r) => `| ${r.join(" | ")} |`),
            ].join("\n");

        case "link_preview":
            if (!block.url) return "";
            return `[${block.title || block.url}](${block.url})${block.description ? `\n${block.description}` : ""}`;

        case "callout":
            return block.title ? `> **${block.title}**\n> ${block.content}` : `> ${block.content}`;

        case "separator":
            return "---";

        case "canvas_block":
            return `**${block.title || "Chart"}**\n` + (block.items || [])
                .map((it) => `- ${it.label}: ${it.value}`)
                .join("\n");

        default:
            return "";
    }
}

export function exportAsMarkdown(node: SynthesisNode): string {
    const lines: string[] = [];

    lines.push(`# ${node.title}`);
    lines.push("");

    if (node.content.summary) {
        lines.push(`> ${node.content.summary}`);
        lines.push("");
    }

    for (const block of node.content.blocks) {
        lines.push(blockToMarkdown(block));
        lines.push("");
    }

    if (node.content.sources && node.content.sources.length > 0) {
        lines.push("## Sources");
        lines.push("");
        for (const source of node.content.sources) {
            lines.push(`- ${source}`);
        }
        lines.push("");
    }

    lines.push(`---`);
    lines.push(`*Generated by Synthesis OS | ${new Date(node.createdAt).toLocaleDateString()}*`);

    return lines.join("\n");
}

export function exportAsJSON(node: SynthesisNode): string {
    return JSON.stringify(
        {
            title: node.title,
            type: node.type,
            query: node.query,
            space: node.spaceId,
            content: node.content,
            createdAt: new Date(node.createdAt).toISOString(),
        },
        null,
        2,
    );
}

export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        // Fallback for older browsers
        try {
            const textarea = document.createElement("textarea");
            textarea.value = text;
            textarea.style.position = "fixed";
            textarea.style.opacity = "0";
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand("copy");
            document.body.removeChild(textarea);
            return true;
        } catch {
            return false;
        }
    }
}

export function downloadAsFile(content: string, filename: string, mimeType: string = "text/plain"): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
